#!/usr/bin/bash
# multi-sync v2.4 2019-02-24

# From https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
lua=$(which lua)
ms=$INSTALL_DIR/multi-sync.lua

export COMPUTERNAME=$(hostname)
export USERNAME=$USER
export CONFIGDIR="$HOME/.config"
export EDITOR=nano

# If Lua and multi-sync.lua are both found, execute
if [[ -f "$lua" && -f "$ms" ]]; then
  $lua $ms "$@"
  exit $?
else
  echo "Lua and/or multi-sync.lua not found"
  exit 1
fi
