#!/usr/bin/env bash

# From https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
lua=$INSTALL_DIR/lua
ms=$INSTALL_DIR/multi-sync.lua

export MS_COMPUTERNAME=$(hostname)
export MS_USERNAME=$USER
export MS_APPDATA="$HOME/.config"
export MS_EDITOR=nano

export LUA_PATH="$INSTALL_DIR/?.lua;"
export LUA_CPATH="$INSTALL_DIR/?.so;"

# If Lua and multi-sync.lua are both found, execute
if [[ -f "$lua" && -f "$ms" ]]; then
  $lua $ms "$@"
  exit $?
else
  echo "Lua and/or multi-sync.lua not found in $INSTALL_DIR"
  exit 1
fi
